# Generated by Django 2.0.2 on 2018-02-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180227_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default/download.jpeg', upload_to='avatars/%Y/%m/%d'),
        ),
    ]
