# Generated by Django 2.0.2 on 2018-03-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='target_ct',
        ),
        migrations.RemoveField(
            model_name='action',
            name='target_id',
        ),
        migrations.AddField(
            model_name='action',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Post'),
        ),
    ]
